#!/usr/bin/env python3
"""Shared stdlib helpers for the companion rulers (plan item 0-7).

Every companion ruler is a separate script frozen by sha256 in rulers/RULER_SET.
This module is frozen with them. bench_decode.py is also listed there, because
the rulers import PHASES, spec_counters and acceptance from it unchanged.

Maintenance:
    python3 rulers/common.py --check           # exit 1 when a frozen file drifted
    python3 rulers/common.py --write --version 2   # re-freeze after an intended change

Bump the version whenever a frozen file changes. Evidence rows carry the version
in "ruler_set"; a drifted tree reports "<version>-dirty" so it cannot pass as frozen.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import statistics
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
import zlib
from pathlib import Path

RULERS_DIR = Path(__file__).resolve().parent
ROOT = RULERS_DIR.parent
MANIFEST = RULERS_DIR / "RULER_SET"
PROMPTS_DIR = RULERS_DIR / "prompts"

DEFAULT_URL = "http://127.0.0.1:8000/v1/chat/completions"
DEFAULT_MODEL = "nvidia/Qwen3.8-Flash-Next-NVFP4"

# Files frozen together. Paths are relative to the recipe root.
FROZEN = (
    "bench_decode.py",
    "bench_diverse.py",
    "bench_sampled.py",
    "bench_structured.py",
    "bench_mixed.py",
    "bench_longctx.py",
    "bench_vision.py",
    "probe_prefix.py",
    "probe_toolstream.py",
    "rulers/common.py",
    "rulers/prompts/diverse.json",
    "rulers/prompts/structured.json",
)


# --------------------------------------------------------------------------- freeze


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_manifest(path: Path = MANIFEST) -> tuple[str, dict[str, str]]:
    version = "0"
    shas: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("version:"):
            version = line.split(":", 1)[1].strip()
            continue
        sha, rel = line.split(None, 1)
        shas[rel.strip()] = sha
    return version, shas


def current_shas() -> dict[str, str]:
    return {rel: file_sha256(ROOT / rel) for rel in FROZEN if (ROOT / rel).is_file()}


def drift() -> list[str]:
    """Frozen paths whose sha differs from the manifest (or are missing)."""
    try:
        _, pinned = read_manifest()
    except OSError:
        return list(FROZEN)
    now = current_shas()
    return sorted(rel for rel in set(pinned) | set(FROZEN) if pinned.get(rel) != now.get(rel))


def write_manifest(version: str) -> None:
    lines = [
        "# RULER_SET: companion ruler manifest (plan 0-7). Generated by",
        "# `python3 rulers/common.py --write --version N`. Do not hand-edit.",
        f"version: {version}",
    ]
    lines += [f"{sha}  {rel}" for rel, sha in current_shas().items()]
    MANIFEST.write_text("\n".join(lines) + "\n")


_IDENTITY_CACHE: dict[str, dict] = {}


def ruler_identity(script: str) -> dict:
    """Fields every evidence row carries: ruler name, RULER_SET version, script sha."""
    if script in _IDENTITY_CACHE:
        return _IDENTITY_CACHE[script]
    path = Path(script).resolve()
    try:
        version, _ = read_manifest()
    except OSError:
        version = "0"
    bad = drift()
    if bad:
        print(f"WARN ruler_set drift: {bad}", file=sys.stderr, flush=True)
    ident = {
        "ruler": path.stem,
        "ruler_set": version if not bad else f"{version}-dirty",
        "ruler_sha": file_sha256(path)[:12],
    }
    _IDENTITY_CACHE[script] = ident
    return ident


# --------------------------------------------------------------------------- output


class Emitter:
    """Print `ROW {json}` lines and append them to an fsync'd JSONL file."""

    def __init__(self, script: str, out: str | None, **meta) -> None:
        self.ident = ruler_identity(script)
        self.meta = meta
        self.out = Path(out) if out else None
        self.lock = threading.Lock()
        if self.out:
            self.out.parent.mkdir(parents=True, exist_ok=True)

    def row(self, kind: str, **fields) -> dict:
        rec = {**self.ident, "kind": kind, "ts": round(time.time(), 3), **self.meta, **fields}
        line = json.dumps(rec, sort_keys=False, default=_json_default)
        with self.lock:
            print("ROW", line, flush=True)
            if self.out:
                with self.out.open("a") as fh:
                    fh.write(line + "\n")
                    fh.flush()
                    os.fsync(fh.fileno())
        return rec

    def summary(self, obj) -> None:
        payload = {**self.ident, **self.meta, "summary": obj}
        print("SUMMARY", json.dumps(payload, indent=2, default=_json_default), flush=True)
        if self.out:
            self.row("summary", summary=obj)


def _json_default(o):
    if isinstance(o, float):
        return round(o, 6)
    return str(o)


def add_common_args(p: argparse.ArgumentParser) -> None:
    p.add_argument("--url", default=DEFAULT_URL)
    p.add_argument("--model", default=DEFAULT_MODEL)
    p.add_argument("--out", default=None, help="append evidence rows to this JSONL file")
    p.add_argument("--label", default="", help="free-text arm label copied into every row")


def base_url(url: str) -> str:
    return url.split("/v1/", 1)[0]


def metrics_url(url: str) -> str:
    return base_url(url) + "/metrics"


def health_ok(url: str, timeout: float = 5.0) -> bool:
    try:
        with urllib.request.urlopen(base_url(url) + "/health", timeout=timeout) as r:
            return r.status == 200
    except (OSError, urllib.error.URLError):
        return False


def require_health(url: str) -> None:
    if not health_ok(url):
        raise SystemExit(f"server not healthy at {base_url(url)}/health")


# --------------------------------------------------------------------------- stats


def pct(values, p: float) -> float | None:
    """Linear-interpolated percentile, p in [0, 100]. None on empty input."""
    vals = sorted(values)
    if not vals:
        return None
    if len(vals) == 1:
        return float(vals[0])
    k = (len(vals) - 1) * p / 100.0
    lo = int(k)
    hi = min(lo + 1, len(vals) - 1)
    return float(vals[lo] + (vals[hi] - vals[lo]) * (k - lo))


def med(values) -> float | None:
    vals = list(values)
    return float(statistics.median(vals)) if vals else None


def rnd(x, nd: int = 3):
    return None if x is None else round(float(x), nd)


def stable_seed(*parts) -> int:
    """seed = hash(prompt_id, rep), stable across processes (unlike hash())."""
    h = hashlib.sha256("\x1f".join(str(p) for p in parts).encode()).digest()
    return int.from_bytes(h[:4], "big") & 0x7FFFFFFF


def text_sha(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8", "replace")).hexdigest()[:16]


# --------------------------------------------------------------------------- metrics


def scrape(url: str, timeout: float = 10.0) -> dict[str, float] | None:
    """Prometheus text -> {metric_name: value summed over label sets}. Skips buckets."""
    try:
        with urllib.request.urlopen(metrics_url(url), timeout=timeout) as resp:
            text = resp.read().decode("utf-8", "replace")
    except (OSError, urllib.error.URLError):
        return None
    return parse_prom(text)


def parse_prom(text: str) -> dict[str, float]:
    out: dict[str, float] = {}
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        name = line.split("{", 1)[0].split(" ", 1)[0]
        if name.endswith("_bucket") or name.endswith("_created"):
            continue
        try:
            val = float(line.rsplit(" ", 1)[1])
        except (IndexError, ValueError):
            continue
        out[name] = out.get(name, 0.0) + val
    return out


def mget(m: dict[str, float] | None, name: str) -> float | None:
    """Read a counter by bare name, accepting the prometheus `_total` suffix."""
    if m is None:
        return None
    for key in (name + "_total", name):
        if key in m:
            return m[key]
    return None


def mdelta(before, after, name: str) -> float | None:
    a, b = mget(after, name), mget(before, name)
    return None if a is None or b is None else a - b


def spec_from_scrape(m: dict[str, float] | None) -> dict[str, float] | None:
    """Same shape as bench_decode.spec_counters(), from one scrape."""
    if m is None:
        return None
    out = {}
    for c in ("num_drafts", "num_draft_tokens", "num_accepted_tokens"):
        v = mget(m, f"vllm:spec_decode_{c}")
        if v is None:
            return None
        out[c] = v
    return out


def busy(url: str) -> float | None:
    """Running + waiting requests right now (other agents share the dev server)."""
    m = scrape(url)
    if m is None:
        return None
    return (mget(m, "vllm:num_requests_running") or 0.0) + (mget(m, "vllm:num_requests_waiting") or 0.0)


# --------------------------------------------------------------------------- streaming


def stream_chat(
    url: str,
    body: dict,
    *,
    timeout: float = 600.0,
    stop: threading.Event | None = None,
    t_ref: float | None = None,
) -> dict:
    """Stream one /v1/chat/completions request and time every delta chunk.

    Mirrors bench_decode.stream_one (include_usage, one chunk = one engine step
    with stream_interval 1) but also counts reasoning and tool-call deltas, keeps
    every chunk timestamp, and never raises: failures land in row["error"].
    `stop` aborts the stream by closing the connection (vLLM aborts the request).
    """
    body = {**body, "stream": True, "stream_options": {"include_usage": True}}
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(), headers={"Content-Type": "application/json"}, method="POST"
    )
    t0 = time.perf_counter()
    row: dict = {
        "t_send": t0 - (t_ref if t_ref is not None else t0),
        "times": [],
        "content_chunks": 0,
        "reasoning_chunks": 0,
        "tool_chunks": 0,
        "tool_arg_len": [],
        "first_content_t": None,
        "finish_reason": None,
        "usage": {},
        "aborted": False,
        "error": None,
    }
    content: list[str] = []
    reasoning: list[str] = []
    calls: dict[int, dict] = {}
    arg_total = 0
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            for raw in resp:
                if stop is not None and stop.is_set():
                    row["aborted"] = True
                    break
                line = raw.decode("utf-8", "replace").strip()
                if not line.startswith("data:"):
                    continue
                payload = line[5:].strip()
                if payload == "[DONE]":
                    break
                try:
                    ev = json.loads(payload)
                except json.JSONDecodeError:
                    continue
                now = time.perf_counter()
                if ev.get("usage"):
                    row["usage"] = ev["usage"]
                choices = ev.get("choices") or []
                if not choices:
                    continue
                ch = choices[0]
                if ch.get("finish_reason"):
                    row["finish_reason"] = ch["finish_reason"]
                delta = ch.get("delta") or {}
                got = False
                c = delta.get("content") or ""
                if c:
                    content.append(c)
                    row["content_chunks"] += 1
                    if row["first_content_t"] is None:
                        row["first_content_t"] = now - t0
                    got = True
                r = delta.get("reasoning") or delta.get("reasoning_content") or ""
                if r:
                    reasoning.append(r)
                    row["reasoning_chunks"] += 1
                    got = True
                for tc in delta.get("tool_calls") or []:
                    slot = calls.setdefault(int(tc.get("index", 0)), {"name": "", "arguments": ""})
                    fn = tc.get("function") or {}
                    if fn.get("name"):
                        slot["name"] += fn["name"]
                    a = fn.get("arguments") or ""
                    if a:
                        slot["arguments"] += a
                        arg_total += len(a)
                    row["tool_chunks"] += 1
                    got = True
                if got:
                    row["times"].append(now - t0)
                    if calls:
                        row["tool_arg_len"].append(arg_total)
    except urllib.error.HTTPError as exc:
        row["error"] = f"HTTP {exc.code}: {exc.read().decode('utf-8', 'replace')[:500]}"
    except Exception as exc:  # noqa: BLE001 - reported per row, never fatal to a wave
        row["error"] = f"{type(exc).__name__}: {exc}"
    row["total_s"] = time.perf_counter() - t0
    row["content"] = "".join(content)
    row["reasoning"] = "".join(reasoning)
    row["tool_calls"] = [calls[k] for k in sorted(calls)]
    return row


def step_stats(row: dict) -> dict:
    """ms/step from chunk timestamps: decode_s / (chunks - 1), plus ITL percentiles."""
    t = row["times"]
    usage = row.get("usage") or {}
    completion = int(usage.get("completion_tokens") or 0)
    out = {
        "ttft_s": rnd(t[0]) if t else None,
        "chunks": len(t),
        "completion_tokens": completion,
        "prompt_tokens": int(usage.get("prompt_tokens") or 0),
        "cached_tokens": ((usage.get("prompt_tokens_details") or {}).get("cached_tokens")),
        "finish_reason": row.get("finish_reason"),
        "error": row.get("error"),
    }
    if len(t) >= 2:
        decode_s = t[-1] - t[0]
        gaps = [(b - a) * 1000.0 for a, b in zip(t, t[1:])]
        out.update(
            decode_s=rnd(decode_s, 4),
            ms_per_step=rnd(decode_s * 1000.0 / (len(t) - 1)),
            tokens_per_step=rnd((completion - 1) / (len(t) - 1)) if completion else None,
            decode_tok_s=rnd((completion - 1) / decode_s) if completion and decode_s > 0 else None,
            itl_p50_ms=rnd(pct(gaps, 50)),
            itl_p99_ms=rnd(pct(gaps, 99)),
            itl_max_ms=rnd(max(gaps)),
        )
    return out


def gaps_in_window(times_abs: list[float], lo: float, hi: float) -> list[float]:
    """Inter-chunk gaps (ms) whose end falls inside [lo, hi] on a shared clock."""
    return [(b - a) * 1000.0 for a, b in zip(times_abs, times_abs[1:]) if lo <= b <= hi]


def chat_body(model: str, messages, max_tokens: int, *, thinking: bool = False, **extra) -> dict:
    if isinstance(messages, str):
        messages = [{"role": "user", "content": messages}]
    body = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0,
        "chat_template_kwargs": {"enable_thinking": thinking},
    }
    body.update(extra)
    return body


# --------------------------------------------------------------------------- prompts


def load_prompts(name: str) -> dict:
    return json.loads((PROMPTS_DIR / f"{name}.json").read_text())


def diverse_items(categories=("prose", "structured"), limit: int | None = None) -> list[dict]:
    data = load_prompts("diverse")
    items: list[dict] = []
    for cat in categories:
        rows = data[cat][:limit] if limit else data[cat]
        for r in rows:
            item = {**r, "category": cat}
            if r.get("tool"):
                item["tools"] = [data["tools"][r["tool"]]]
            items.append(item)
    return items


def item_body(model: str, item: dict, max_tokens: int, **extra) -> dict:
    body = chat_body(model, item["prompt"], max_tokens, **extra)
    if item.get("tools"):
        body["tools"] = item["tools"]
        body["tool_choice"] = "auto"
    return body


_WORDS = (
    "the of and to in a is that for it as was with be by on not he this are or his from at "
    "which but have an they you were her she there been one all we their has would when who "
    "will more no if out so said what up its about into than them can only other new some "
    "could time these two may then do first any my now such like our over man me even most "
    "made after also did many before must through back years where much your way well down "
    "should because each just those people how too little state good very make world still "
    "own see men work long get here between both life being under never day same another know "
    "while last might us great old year off come since against go came right used take three "
    "river harbour lantern copper meadow ledger orchard quarry signal valley engine station "
    "archive bridge compass furnace glacier market harvest island journal kettle library"
).split()


def filler_text(n_words: int, seed) -> str:
    """Deterministic pseudo-prose. Distinct seeds give distinct (uncached) text."""
    rng = random.Random(f"filler:{seed}")
    out: list[str] = []
    n = 0
    while n < n_words:
        k = rng.randint(8, 22)
        words = [rng.choice(_WORDS) for _ in range(k)]
        words[0] = words[0].capitalize()
        out.append(" ".join(words) + ".")
        n += k
    return " ".join(out)


def count_tokens(url: str, model: str, messages) -> int | None:
    """Token count via vLLM's /tokenize (chat template applied). None when unavailable."""
    body = {"model": model, "messages": messages, "add_generation_prompt": True}
    req = urllib.request.Request(
        base_url(url) + "/tokenize",
        data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            data = json.loads(resp.read())
    except (OSError, urllib.error.URLError, ValueError):
        return None
    return int(data.get("count") or len(data.get("tokens") or []))


def long_prompt(
    url: str,
    model: str,
    target_tokens: int,
    seed,
    *,
    question: str,
    needles: list[tuple[float, str]] | None = None,
) -> tuple[str, int | None]:
    """Build a user prompt of ~target_tokens: unique salt first (defeats prefix
    reuse across seeds), filler, needle sentences at depth fractions, question last.
    Calibrated against /tokenize; falls back to 1.3 tokens/word when it is absent."""

    def build(n_words: int) -> str:
        body = filler_text(n_words, seed)
        if needles:
            words = body.split(" ")
            for depth, sentence in sorted(needles, reverse=True):
                i = max(1, int(len(words) * depth))
                while i < len(words) and not words[i - 1].endswith("."):
                    i += 1
                words.insert(i, sentence)
            body = " ".join(words)
        return f"[doc {seed}]\n{body}\n\n{question}"

    n_words = max(16, int(target_tokens / 1.3))
    text = build(n_words)
    got = count_tokens(url, model, [{"role": "user", "content": text}])
    if got:
        n_words = max(16, int(n_words * target_tokens / got))
        text = build(n_words)
        got = count_tokens(url, model, [{"role": "user", "content": text}])
    return text, got


# --------------------------------------------------------------------------- images


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (
        len(data).to_bytes(4, "big")
        + tag
        + data
        + (zlib.crc32(tag + data) & 0xFFFFFFFF).to_bytes(4, "big")
    )


def grid_png(width: int, height: int, *, cols: int = 8, rows: int = 6, salt=0) -> bytes:
    """Stdlib RGB PNG: a cols x rows grid of colour blocks. `salt` changes the
    colours, so each send is a distinct image (defeats vLLM's mm processor cache)."""
    rng = random.Random(f"grid:{salt}")
    palette = [[bytes(rng.randrange(256) for _ in range(3)) for _ in range(cols)] for _ in range(rows)]
    comp = zlib.compressobj(6)
    parts = [b"\x89PNG\r\n\x1a\n", _png_chunk(b"IHDR", width.to_bytes(4, "big") + height.to_bytes(4, "big") + b"\x08\x02\x00\x00\x00")]
    idat: list[bytes] = []
    for r in range(rows):
        y0, y1 = r * height // rows, (r + 1) * height // rows
        line = bytearray(b"\x00")
        for c in range(cols):
            x0, x1 = c * width // cols, (c + 1) * width // cols
            line += palette[r][c] * (x1 - x0)
        idat.append(comp.compress(bytes(line) * (y1 - y0)))
    idat.append(comp.flush())
    parts.append(_png_chunk(b"IDAT", b"".join(idat)))
    parts.append(_png_chunk(b"IEND", b""))
    return b"".join(parts)


# --------------------------------------------------------------------------- host sampling


def run_cmd(cmd: list[str], timeout: float = 15.0) -> str:
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, check=False).stdout
    except (OSError, subprocess.TimeoutExpired) as exc:
        return f"ERR {exc}"


class HostSampler(threading.Thread):
    """Every `period` s: `free -h` and one vmstat line on the head and (read-only,
    over ssh BatchMode) on the worker. Writes a JSONL log next to --out."""

    CMD = "free -h; vmstat 1 2 | tail -1"

    def __init__(self, log_path: Path, worker: str | None, period: float = 5.0) -> None:
        super().__init__(daemon=True)
        self.log_path = log_path
        self.worker = worker
        self.period = period
        self.halt = threading.Event()
        self.samples = 0

    def _sample(self, host: str | None) -> str:
        if host is None:
            return run_cmd(["sh", "-c", self.CMD])
        return run_cmd(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=5", host, self.CMD])

    def run(self) -> None:
        self.log_path.parent.mkdir(parents=True, exist_ok=True)
        with self.log_path.open("a") as fh:
            while not self.halt.is_set():
                t = time.time()
                hosts = [("head", None)] + ([("worker", self.worker)] if self.worker else [])
                for name, host in hosts:
                    fh.write(json.dumps({"ts": round(t, 3), "node": name, "out": self._sample(host)}) + "\n")
                fh.flush()
                self.samples += 1
                self.halt.wait(max(0.0, self.period - (time.time() - t)))

    def stop(self) -> None:
        self.halt.set()
        self.join(timeout=30)


# --------------------------------------------------------------------------- CLI


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="exit 1 when a frozen file drifted")
    g.add_argument("--write", action="store_true", help="rewrite RULER_SET from the current tree")
    p.add_argument("--version", help="RULER_SET version to write (required with --write)")
    args = p.parse_args()
    if args.write:
        if not args.version:
            p.error("--write needs --version")
        write_manifest(args.version)
        print(f"wrote {MANIFEST} version {args.version}")
        return 0
    bad = drift()
    version, _ = read_manifest()
    if bad:
        print(f"RULER_SET {version} drift: {bad}", file=sys.stderr)
        return 1
    print(f"RULER_SET {version} ok ({len(FROZEN)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
