#!/usr/bin/env python3
"""Generate chat_template_alias.jinja from the checkpoint chat template.

The stock template accepts reasoning_effort xhigh/medium/low only (finding
F21). vLLM's Chat Completions API also accepts minimal/high/max, and the
Anthropic /v1/messages effort high/max, so those raise HTTP 400 whenever
thinking resolves on. The copy maps high->xhigh, max->xhigh, minimal->low
before the stock check. Every other input renders byte-identical to stock
(tests/test_alias_template.py). Serve it with --chat-template.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_SHA = "fab0aecb760cec45227f6656abcaafa11abca87a"
STOCK = (
    Path.home()
    / ".cache/huggingface/hub/models--nvidia--Qwen3.8-Flash-Next-NVFP4/snapshots"
    / SNAPSHOT_SHA
    / "chat_template.jinja"
)
STOCK_SHA256 = "c3cf9e34abf4f9e36c2d72165aa9c132d3e2a725b6c2586aaa3a8af9d7a81041"
OUT = ROOT / "chat_template_alias.jinja"

HEADER = (
    "{#- GENERATED by tools/make_alias_template.py; do not hand-edit.\n"
    f"    source: nvidia/Qwen3.8-Flash-Next-NVFP4@{SNAPSHOT_SHA} chat_template.jinja\n"
    f"    source_sha256: {STOCK_SHA256}\n"
    "    change: reasoning_effort alias high->xhigh, max->xhigh, minimal->low (F21) -#}\n"
)
ANCHOR = "    {%- set resolved_reasoning_effort = reasoning_effort|default('xhigh') %}\n"
ALIAS = (
    "    {%- if resolved_reasoning_effort in ('high', 'max') %}\n"
    "        {%- set resolved_reasoning_effort = 'xhigh' %}\n"
    "    {%- elif resolved_reasoning_effort == 'minimal' %}\n"
    "        {%- set resolved_reasoning_effort = 'low' %}\n"
    "    {%- endif %}\n"
)


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def make(stock: str) -> str:
    got = sha256(stock)
    if got != STOCK_SHA256:
        raise SystemExit(f"make_alias_template: stock sha256 {got} != {STOCK_SHA256}")
    if stock.count(ANCHOR) != 1:
        raise SystemExit("make_alias_template: reasoning_effort anchor not found")
    return HEADER + stock.replace(ANCHOR, ANCHOR + ALIAS, 1)


def unmake(alias: str) -> str:
    """Invert make(); tests use it to recover stock and check its sha256."""
    if not alias.startswith(HEADER):
        raise ValueError("alias header missing or stale")
    body = alias[len(HEADER) :]
    if body.count(ANCHOR + ALIAS) != 1:
        raise ValueError("alias block missing")
    return body.replace(ANCHOR + ALIAS, ANCHOR, 1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--stock", type=Path, default=STOCK)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if --out is stale"
    )
    args = ap.parse_args()
    text = make(args.stock.read_text())
    if args.check:
        if not args.out.exists() or args.out.read_text() != text:
            print(f"make_alias_template: {args.out} is stale", file=sys.stderr)
            return 1
        print(f"make_alias_template: {args.out} up to date")
        return 0
    args.out.write_text(text)
    print(f"make_alias_template: wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
